#!/usr/bin/env python
# encoding: utf-8

name = "seed_edge"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "[Pt]=NN=[Pt] <=> N_X + N_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.77e+11,'1/s'), n=0.06, Ea=(452538,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 3 N2X2 <=> NX-2 + NX in Surface_Bidentate_Dissociation/training
    This reaction matched rate rule [Combined]
    family: Surface_Bidentate_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 3 N2X2 <=> NX-2 + NX in Surface_Bidentate_Dissociation/training
This reaction matched rate rule [Combined]
family: Surface_Bidentate_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 1,
    label = "X + N2_X <=> [Pt]=NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(4.184,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 2,
    label = "X + X + NO2 <=> NO2JXX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.146, n=0.201, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
    Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 3,
    label = "X + X + N2 <=> [Pt]=NN=[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.146, n=0.201, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
    Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 4,
    label = "N_X + NO-h_ads <=> O_X + [Pt]=NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.53491e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
""",
)

entry(
    index = 5,
    label = "X + X + HONO <=> O_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ONR;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ONR;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 6,
    label = "O_X + HONO-2 <=> NO_X + OOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.36667e+20,'cm^2/(mol*s)'), n=0, Ea=(67.543,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [N-R;*=O] for rate rule [N-O;*=O]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;*=O] for rate rule [N-O;*=O]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 7,
    label = "N_X + HONO-2 <=> NO_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.17675e+14,'m^2/(mol*s)'), n=0.208794, Ea=(118.607,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [N-R;*#N] for rate rule [N-O;*#N]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;*#N] for rate rule [N-O;*#N]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 8,
    label = "X + HONO-2 <=> O_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.88316e+10,'m^2/(mol*s)'), n=1.39534, Ea=(-20.4157,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 6 used for ONR;VacantSite
    Exact match found for rate rule [ONR;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_Double_vdW"""),
    longDesc = 
"""
From training reaction 6 used for ONR;VacantSite
Exact match found for rate rule [ONR;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_Double_vdW
""",
)

entry(
    index = 9,
    label = "X + X + HNNOH <=> NH_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [NN;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [NN;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 10,
    label = "X + HNNOH-2 <=> NH_X + NOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.87e+21,'cm^2/(mol*s)'), n=0, Ea=(70.4377,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 9 used for AdsorbateVdW;VacantSite
    Exact match found for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW"""),
    longDesc = 
"""
From training reaction 9 used for AdsorbateVdW;VacantSite
Exact match found for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
""",
)

entry(
    index = 11,
    label = "X + X + ONOOH <=> NO_X + OOH_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0304631, n=0.077, Ea=(18.828,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-N;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-N;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 12,
    label = "X + HO2 <=> OOH_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.00480264, n=0.684667, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [O;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 13,
    label = "OH_X + NH2NO2 <=> NO2OH-2 + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.56667e+21,'cm^2/(mol*s)'), n=0, Ea=(33.7715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [N-R;*O-H] for rate rule [N-N;*O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;*O-H] for rate rule [N-N;*O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 14,
    label = "H_X + H2N2O3X <=> NO2OH-2 + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(9.48698e+16,'m^2/(mol*s)'), n=0.0693333, Ea=(36.7735,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N-R;Abstracting] for rate rule [N-O;Abstracting]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;Abstracting] for rate rule [N-O;Abstracting]
Euclidian distance = 1.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 15,
    label = "NH_X + NO2OH-2 <=> OH_X + HN2O2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.24812e+12,'m^2/(mol*s)'), n=0.968861, Ea=(87.7573,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 9 used for O-R;*=NH
    Exact match found for rate rule [O-R;*=NH]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 9 used for O-R;*=NH
Exact match found for rate rule [O-R;*=NH]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 16,
    label = "NH_X + NO2OH-2 <=> H_X + HN2O3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.20477e+12,'m^2/(mol*s)'), n=0.894608, Ea=(210.779,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=NH]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=NH]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 17,
    label = "N_X + NO2OH-2 <=> N2O2X + OH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.09775e+11,'m^2/(mol*s)'), n=1.02854, Ea=(152.305,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 10 used for O-R;*#N
    Exact match found for rate rule [O-R;*#N]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 10 used for O-R;*#N
Exact match found for rate rule [O-R;*#N]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 18,
    label = "N_X + NO2OH-2 <=> N2O3X + H_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5.90531e+12,'m^2/(mol*s)'), n=0.618666, Ea=(141.12,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*#N]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*#N]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 19,
    label = "NO2NO + OH_X <=> NO_X + NO2OH-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.56667e+21,'cm^2/(mol*s)'), n=0, Ea=(33.7715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [N-R;*O-H] for rate rule [N-N;*O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;*O-H] for rate rule [N-N;*O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 20,
    label = "NHO_X + NO2OH-2 <=> OH_X + HN2O3X-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.7875e+20,'cm^2/(mol*s)'), n=-0.1992, Ea=(68.9269,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [HNO;O-R]
    Euclidian distance = 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [HNO;O-R]
Euclidian distance = 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 21,
    label = "NHO_X + NO2OH-2 <=> OH_X + HN2O3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(9.87246e+14,'m^2/(mol*s)'), n=0.0102509, Ea=(132.426,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N;Adsorbate2] for rate rule [ONR;O-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [N;Adsorbate2] for rate rule [ONR;O-R]
Euclidian distance = 2.23606797749979
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 22,
    label = "NO2OH-2 + CO_X <=> OH_X + CNO3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2e+19,'cm^2/(mol*s)'), n=0, Ea=(152.716,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 62 used for O-R;*=C=R
    Exact match found for rate rule [O-R;*=C=R]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 62 used for O-R;*=C=R
Exact match found for rate rule [O-R;*=C=R]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 23,
    label = "H_X + NO2OH-2 <=> OH_X + HNO2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(60.9818,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O-R;Abstracting]
    Euclidian distance = 0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [O-R;Abstracting]
Euclidian distance = 0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 24,
    label = "NO2OH-2 + HCN_X <=> OH_X + CHN2O2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(9.87246e+14,'m^2/(mol*s)'), n=0.0102509, Ea=(25.5277,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N;Adsorbate2] for rate rule [N#CR;O-R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [N;Adsorbate2] for rate rule [N#CR;O-R]
Euclidian distance = 3.1622776601683795
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 25,
    label = "NO2OH-2 + HCN_X <=> H_X + CHN2O3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(9.87246e+14,'m^2/(mol*s)'), n=0.0102509, Ea=(67.4607,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N;Adsorbate2] for rate rule [N#CR;Adsorbate2]
    Euclidian distance = 3.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 66.8 to 67.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [N;Adsorbate2] for rate rule [N#CR;Adsorbate2]
Euclidian distance = 3.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 66.8 to 67.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 26,
    label = "NO2OH-2 + HCN_X <=> OH_X + CHN2O2X-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.7875e+20,'cm^2/(mol*s)'), n=-0.1992, Ea=(98.3859,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C;O-R] for rate rule [RC#N;O-R]
    Euclidian distance = 3.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C;O-R] for rate rule [RC#N;O-R]
Euclidian distance = 3.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 27,
    label = "NO2OH-2 + HCN_X <=> H_X + CHN2O3X-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.7875e+16,'m^2/(mol*s)'), n=-0.1992, Ea=(279.054,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C;Adsorbate2] for rate rule [RC#N;Adsorbate2]
    Euclidian distance = 3.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C;Adsorbate2] for rate rule [RC#N;Adsorbate2]
Euclidian distance = 3.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 28,
    label = "OH_X + CN2O2X <=> NO2OH-2 + CN_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.56667e+21,'cm^2/(mol*s)'), n=0, Ea=(33.7715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;*O-H] for rate rule [C-R;*O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [Donating;*O-H] for rate rule [C-R;*O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 29,
    label = "H_X + CN2O3X <=> NO2OH-2 + CN_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.83941e+16,'m^2/(mol*s)'), n=0.0450667, Ea=(49.724,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-O;Abstracting]
    Euclidian distance = 2.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-O;Abstracting]
Euclidian distance = 2.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 30,
    label = "NO2OH-2 + C_X <=> OH_X + CNO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.955e+20,'cm^2/(mol*s)'), n=-0.3882, Ea=(386.451,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 52 used for O-R;*$C
    Exact match found for rate rule [O-R;*$C]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 52 used for O-R;*$C
Exact match found for rate rule [O-R;*$C]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 31,
    label = "NO2OH-2 + C_X <=> H_X + CNO3X-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.955e+20,'cm^2/(mol*s)'), n=-0.3882, Ea=(71.128,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*$C]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*$C]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 32,
    label = "NO2OH-2 + CH2O_X <=> OH_X + CH2NO3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.7875e+20,'cm^2/(mol*s)'), n=-0.1992, Ea=(72.8155,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
    Euclidian distance = 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
Euclidian distance = 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 33,
    label = "NO2OH-2 + CH2O_X <=> OH_X + CH2NO3X-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.7875e+20,'cm^2/(mol*s)'), n=-0.1992, Ea=(119.358,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C=O;O-R] for rate rule [2R-C=O;O-R]
    Euclidian distance = 1.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;O-R] for rate rule [2R-C=O;O-R]
Euclidian distance = 1.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 34,
    label = "OH_X + CHNO3X <=> NO2OH-2 + HCO_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.56667e+21,'cm^2/(mol*s)'), n=0, Ea=(33.7715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;*O-H] for rate rule [C-R;*O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [Donating;*O-H] for rate rule [C-R;*O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 35,
    label = "NO-h_ads + NO2OH-2 <=> NO2NOXX + OH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.24812e+12,'m^2/(mol*s)'), n=0.968861, Ea=(138.135,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*=N] for rate rule [O-R;*=NO]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=N] for rate rule [O-R;*=NO]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 36,
    label = "NO-h_ads + NO2OH-2 <=> O_X + HN2O3X2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(609.58,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;Adsorbate1] for rate rule [O=N;*O-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 602.9 to 609.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O;Adsorbate1] for rate rule [O=N;*O-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 602.9 to 609.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 37,
    label = "NO-h_ads + NO2OH-2 <=> O_X + HN2O3X2-2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(181.17,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=O;*O-R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 180.6 to 181.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=O;*O-R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 180.6 to 181.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 38,
    label = "X + X + O2(S) <=> O2_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.073, n=0.201, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
    Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 39,
    label = "X + O2(S)-2 <=> O2_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_vdW_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_vdW_to_Bidentate
""",
)

entry(
    index = 40,
    label = "X + [Pt]OOO[Pt] <=> O_X + O2_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.47172e+17,'m^2/(mol*s)'), n=0.624, Ea=(130.107,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [O;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 41,
    label = "O2_ads + NH_X <=> O_X + HNOXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(7.06982e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [R-N=*;*R-O]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [R-N=*;*R-O]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 42,
    label = "X + HNOOXX <=> O2_ads + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.34e+17,'cm^2/(mol*s)'), n=1.942, Ea=(121.577,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 49 used for N;VacantSite
    Exact match found for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 49 used for N;VacantSite
Exact match found for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 43,
    label = "X + [Pt]OON=[Pt] <=> O2_ads + N_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.34e+17,'cm^2/(mol*s)'), n=1.942, Ea=(121.577,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 49 used for N;VacantSite
    Exact match found for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 49 used for N;VacantSite
Exact match found for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 44,
    label = "O2_ads + NO_X <=> X + [Pt]OOON=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.30976e+17,'m^2/(mol*s)'), n=0.195797, Ea=(344.34,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [*N;Adsorbate2] for rate rule [*N;O-*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Beta
    Ea raised from 343.7 to 344.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [*N;Adsorbate2] for rate rule [*N;O-*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Beta
Ea raised from 343.7 to 344.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 45,
    label = "O2_ads + NHO_X <=> X + [Pt]OONO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.90034e+17,'m^2/(mol*s)'), n=-0.145627, Ea=(237.809,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;O*] for rate rule [HNO;O*]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [O;O*] for rate rule [HNO;O*]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 46,
    label = "O2_ads + NHO_X <=> X + [Pt]NOOO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01537e+12,'m^2/(mol*s)'), n=0.177632, Ea=(316.239,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N;Adsorbate1] for rate rule [ONR;O*]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N;Adsorbate1] for rate rule [ONR;O*]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 47,
    label = "O2_ads + NHO_X <=> O_X + HNO2JJXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(128.453,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;Adsorbate1] for rate rule [HNO;*O-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O;Adsorbate1] for rate rule [HNO;*O-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 48,
    label = "O2_ads + NHO_X <=> O_X + HNOOXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(187.74,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [ONR;*O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [ONR;*O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 49,
    label = "O2_ads + N2O_X <=> X + N2O3X2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.90034e+17,'m^2/(mol*s)'), n=-0.145627, Ea=(213.396,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;O*] for rate rule [O=N;O*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from 207.8 to 213.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O;O*] for rate rule [O=N;O*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from 207.8 to 213.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 50,
    label = "O2_ads + N2O_X <=> X + N2O3X2-2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01537e+12,'m^2/(mol*s)'), n=0.177632, Ea=(249.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N;Adsorbate1] for rate rule [N=O;O*]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N;Adsorbate1] for rate rule [N=O;O*]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 51,
    label = "O2_ads + N2O_X <=> O_X + N2O2X2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(58.7758,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;Adsorbate1] for rate rule [O=N;*O-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 56.5 to 58.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O;Adsorbate1] for rate rule [O=N;*O-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 56.5 to 58.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 52,
    label = "O2_ads + N2O_X <=> O_X + N2O2X2-2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(110.876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=O;*O-R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=O;*O-R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 53,
    label = "O2_ads + N2O_X <=> X + N2O3X2-3",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01537e+12,'m^2/(mol*s)'), n=0.177632, Ea=(249.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [NN;Adsorbate1] for rate rule [NN;O*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [NN;Adsorbate1] for rate rule [NN;O*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 54,
    label = "O2_ads + N2O_X <=> X + N2O3X2-4",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01537e+12,'m^2/(mol*s)'), n=0.177632, Ea=(249.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [NN;Adsorbate1] for rate rule [NN;O*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [NN;Adsorbate1] for rate rule [NN;O*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 55,
    label = "O2_ads + N2O_X <=> O_X + ONNOJJ_cisXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(577.604,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [NN;*O-R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 576.9 to 577.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [NN;*O-R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 576.9 to 577.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 56,
    label = "O2_ads + N2O_X <=> O_X + N2O2X2-3",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(110.876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [NN;*O-R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [NN;*O-R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 57,
    label = "O2_ads + N2_X <=> O_X + N2OXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(7.06982e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [N=*;*R-O]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [N=*;*R-O]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 58,
    label = "X + N2O2X2-2 <=> O2_ads + N2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.34e+17,'cm^2/(mol*s)'), n=1.942, Ea=(228.285,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 49 used for N;VacantSite
    Exact match found for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 49 used for N;VacantSite
Exact match found for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 59,
    label = "O2_ads + N2_X <=> X + N2O2X2-4",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.35598e+17,'m^2/(mol*s)'), n=0.0978984, Ea=(133.691,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [Adsorbate1;O-*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [Adsorbate1;O-*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 60,
    label = "O2_ads + CO_X <=> O_X + CO2XX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.78e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;Donating] for rate rule [C=*;*R-O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;Donating] for rate rule [C=*;*R-O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 61,
    label = "X + CO3t2XX <=> O2_ads + CO_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.3e+20,'cm^2/(mol*s)'), n=-0.4123, Ea=(31.38,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [C-O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C-O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 62,
    label = "O2_ads + CO_X <=> X + [Pt]OOOC#[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(7.598e+17,'m^2/(mol*s)'), n=0, Ea=(301.897,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;O-*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;O-*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 63,
    label = "O2_ads + CO2_X <=> O_X + CO3t1XX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(7.256e+16,'m^2/(mol*s)'), n=0, Ea=(145.301,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 144.8 to 145.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 144.8 to 145.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 64,
    label = "O2_ads + CO2_X <=> O_X + CO3t2XX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.3e+19,'cm^2/(mol*s)'), n=0.097, Ea=(285.546,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 3 used for CO2;*O-R
    Exact match found for rate rule [CO2;*O-R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 284.7 to 285.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
From training reaction 3 used for CO2;*O-R
Exact match found for rate rule [CO2;*O-R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 284.7 to 285.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 65,
    label = "O2_ads + HCN <=> [Pt]OOC=N[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 66,
    label = "O2_ads + HCN <=> [Pt]OON=C[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(275.759,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 274.2 to 275.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 274.2 to 275.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 67,
    label = "O2_ads + HCN_X <=> X + [Pt]OOC=N[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01537e+12,'m^2/(mol*s)'), n=0.177632, Ea=(249.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N;Adsorbate1] for rate rule [N#CR;O*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N;Adsorbate1] for rate rule [N#CR;O*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 68,
    label = "O2_ads + HCN_X <=> X + [Pt]OON=C[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(5.207e+13,'m^2/(mol*s)'), n=-0.00369223, Ea=(301.819,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C;Adsorbate1] for rate rule [RC#N;O*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from -29.1 to 301.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [C;Adsorbate1] for rate rule [RC#N;O*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from -29.1 to 301.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 69,
    label = "O2_ads + HCN_X <=> O_X + [Pt]OC=N[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(110.876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [N#CR;*O-R]
    Euclidian distance = 4.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [N#CR;*O-R]
Euclidian distance = 4.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 70,
    label = "O2_ads + HCN_X <=> O_X + HCNOJJXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(132.391,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C;*O-R] for rate rule [RC#N;*O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [C;*O-R] for rate rule [RC#N;*O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 71,
    label = "O2_ads + CN_X <=> X + [Pt]OON=C=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.524e+17,'m^2/(mol*s)'), n=0, Ea=(452.836,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [*-C;Adsorbate2] for rate rule [*-C;O-*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Beta
    Ea raised from 451.5 to 452.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [*-C;Adsorbate2] for rate rule [*-C;O-*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Beta
Ea raised from 451.5 to 452.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 72,
    label = "O2_ads + C_X <=> O_X + COXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.86e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*R-O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*R-O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 73,
    label = "X + [Pt]OOC#[Pt] <=> O2_ads + C_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.3e+20,'cm^2/(mol*s)'), n=-0.4123, Ea=(31.38,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [C-O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C-O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 74,
    label = "O2_ads + CH2O <=> [Pt]OCOO[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(309.331,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 75,
    label = "O2_ads + CH2O <=> [Pt]COOO[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(300.759,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 297.7 to 300.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 297.7 to 300.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 76,
    label = "O2_ads + CH2O_X <=> X + [Pt]OCOO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.352e+18,'m^2/(mol*s)'), n=0, Ea=(361.583,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 8 used for O=C;O*
    Exact match found for rate rule [O=C;O*]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
From training reaction 8 used for O=C;O*
Exact match found for rate rule [O=C;O*]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 77,
    label = "O2_ads + CH2O_X <=> X + [Pt]COOO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.77821e+11,'m^2/(mol*s)'), n=-0.00738446, Ea=(351.386,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;O*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from -63.7 to 351.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;O*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from -63.7 to 351.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 78,
    label = "O2_ads + CH2O_X <=> O_X + [Pt]OCO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(54.9689,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 79,
    label = "O2_ads + CH2O_X <=> O_X + [Pt]COO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(179.744,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C=O;*O-R] for rate rule [2R-C=O;*O-R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 179.4 to 179.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [C=O;*O-R] for rate rule [2R-C=O;*O-R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 179.4 to 179.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 80,
    label = "O2_ads + HCO_X <=> X + [Pt]OOOC=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.524e+17,'m^2/(mol*s)'), n=0, Ea=(496.236,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;O-*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Beta
    Ea raised from 495.6 to 496.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;O-*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Beta
Ea raised from 495.6 to 496.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 81,
    label = "O_X + ONNO_cisXX <=> O2_ads + N2O_X-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.48135e+17,'m^2/(mol*s)'), n=0, Ea=(58.1352,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;Donating] for rate rule [O;*R-O]
    Euclidian distance = 1.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [O;Donating] for rate rule [O;*R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 82,
    label = "X + [Pt]N(N=O)OO[Pt] <=> O2_ads + N2O_X-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.34e+17,'cm^2/(mol*s)'), n=1.942, Ea=(121.577,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 49 used for N;VacantSite
    Exact match found for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 49 used for N;VacantSite
Exact match found for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 83,
    label = "O2_ads + N2O_X-2 <=> X + N2O3X2-4",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.35598e+17,'m^2/(mol*s)'), n=0.0978984, Ea=(210.489,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [Adsorbate1;O-*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Beta
    Ea raised from 205.0 to 210.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [Adsorbate1;O-*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Beta
Ea raised from 205.0 to 210.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 84,
    label = "O2_ads + C2N2 <=> [Pt]OOC(=N[Pt])C#N",
    degeneracy = 4.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 85,
    label = "O2_ads + C2N2 <=> [Pt]C(=NOO[Pt])C#N",
    degeneracy = 4.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(228.545,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 227.5 to 228.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 227.5 to 228.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 86,
    label = "O2_ads + C2N2_X <=> X + [Pt]OOC(=N[Pt])C#N",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.03073e+12,'m^2/(mol*s)'), n=0.177632, Ea=(249.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N;Adsorbate1] for rate rule [N#CR;O*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N;Adsorbate1] for rate rule [N#CR;O*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 87,
    label = "O2_ads + C2N2_X <=> X + [Pt]C(=NOO[Pt])C#N",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(1.0414e+14,'m^2/(mol*s)'), n=-0.00369223, Ea=(232.101,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C;Adsorbate1] for rate rule [RC#N;O*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Addition_Single_vdW
    Ea raised from -29.1 to 232.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [C;Adsorbate1] for rate rule [RC#N;O*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Addition_Single_vdW
Ea raised from -29.1 to 232.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 88,
    label = "O2_ads + C2N2_X <=> O_X + [Pt]OC(=N[Pt])C#N",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.3e+19,'cm^2/(mol*s)'), n=0.097, Ea=(110.876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [N#CR;*O-R]
    Euclidian distance = 4.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [N#CR;*O-R]
Euclidian distance = 4.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 89,
    label = "O2_ads + C2N2_X <=> O_X + [Pt]C(=NO[Pt])C#N",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.3e+19,'cm^2/(mol*s)'), n=0.097, Ea=(110.876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C;*O-R] for rate rule [RC#N;*O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [C;*O-R] for rate rule [RC#N;*O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 90,
    label = "X + O2_ads <=> O_X + O(T)XX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.47172e+17,'m^2/(mol*s)'), n=0.624, Ea=(130.107,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [O;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 91,
    label = "O2_ads + N2 <=> N2O2X2-4",
    degeneracy = 4.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(292.628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 290.1 to 292.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 290.1 to 292.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 92,
    label = "O2_ads + N2O <=> N2O3X2",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(239.838,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 234.9 to 239.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 234.9 to 239.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 93,
    label = "O2_ads + N2O <=> N2O3X2-2",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(266.81,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 266.0 to 266.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 266.0 to 266.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 94,
    label = "O2_ads + N2O <=> N2O3X2-3",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(190.172,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 188.7 to 190.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 188.7 to 190.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 95,
    label = "O2_ads + N2O <=> N2O3X2-4",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(185.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 178.5 to 185.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R#R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 178.5 to 185.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 96,
    label = "O_X + [Pt]ON(O[Pt])[Pt] <=> O2_ads + NO-h_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.96271e+17,'m^2/(mol*s)'), n=0, Ea=(58.1352,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;Donating] for rate rule [O;*R-O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [O;Donating] for rate rule [O;*R-O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 97,
    label = "X + [Pt]OON(O[Pt])[Pt] <=> O2_ads + NO-h_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.34e+17,'cm^2/(mol*s)'), n=1.942, Ea=(121.577,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 49 used for N;VacantSite
    Exact match found for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 49 used for N;VacantSite
Exact match found for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 98,
    label = "O2_ads + NH2NO <=> [Pt]OON(O[Pt])N",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(186.099,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 99,
    label = "O2_ads + NH2NO <=> [Pt]OOON([Pt])N",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(223.064,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 221.3 to 223.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 221.3 to 223.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 100,
    label = "O2_ads + NH2NO <=> H2N2O3X2",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(131.27,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 129.7 to 131.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 129.7 to 131.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 101,
    label = "O2_ads + NH2NO <=> H2N2O3X2-2",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(189.782,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 186.4 to 189.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 186.4 to 189.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 102,
    label = "O2_ads + HONO-2 <=> O_X + [Pt]ON(O[Pt])O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(47.9341,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O;Adsorbate1] for rate rule [HONO;*O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O;Adsorbate1] for rate rule [HONO;*O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 103,
    label = "O2_ads + HONO-2 <=> O_X + [Pt]OON([Pt])O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(117.494,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [ONOH;*O-R]
    Euclidian distance = 5.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 116.2 to 117.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [ONOH;*O-R]
Euclidian distance = 5.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 116.2 to 117.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 104,
    label = "O2_ads + HNNOH <=> [Pt]OONN([Pt])O",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(138.56,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 135.3 to 138.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 135.3 to 138.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 105,
    label = "O2_ads + HNNOH <=> [Pt]OON(N[Pt])O",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(140.073,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 138.3 to 140.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 138.3 to 140.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 106,
    label = "O2_ads + HNNOH-2 <=> X + [Pt]OONN([Pt])O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01537e+12,'m^2/(mol*s)'), n=0.177632, Ea=(249.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [NN;Adsorbate1] for rate rule [N=N;O*]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [NN;Adsorbate1] for rate rule [N=N;O*]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 107,
    label = "O2_ads + HNNOH-2 <=> X + [Pt]OON(N[Pt])O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01537e+12,'m^2/(mol*s)'), n=0.177632, Ea=(249.305,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [NN;Adsorbate1] for rate rule [N=N;O*]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [NN;Adsorbate1] for rate rule [N=N;O*]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 108,
    label = "O2_ads + HNNOH-2 <=> O_X + [Pt]ONN([Pt])O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(110.876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=N;*O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=N;*O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 109,
    label = "O2_ads + HNNOH-2 <=> O_X + [Pt]NN(O[Pt])O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.15e+19,'cm^2/(mol*s)'), n=0.097, Ea=(110.876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=N;*O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*O-R] for rate rule [N=N;*O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

