#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + NH3 <=> NH3_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 4 X + H3N <=> H3NX in Surface_Adsorption_vdW/training
    This reaction matched rate rule [Adsorbate;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 4 X + H3N <=> H3NX in Surface_Adsorption_vdW/training
This reaction matched rate rule [Adsorbate;VacantSite]
family: Surface_Adsorption_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 1,
    label = "X + X + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.89e+21,'cm^5/(mol^2*s)'), n=-0.5, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 2,
    label = "OX + NH3_ads <=> HOX + NH2_ads",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.01e+21,'cm^2/(mol*s)'), n=0, Ea=(67543,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 8 O* + H3NX <=> H2NX + OH_4* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 8 O* + H3NX <=> H2NX + OH_4* in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*=O]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 3,
    label = "X + H2O <=> H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.75, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 4,
    label = "OX + H2OX <=> HOX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+20,'cm^2/(mol*s)'), n=0, Ea=(43100,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 5,
    label = "HOX + NH3_ads <=> H2OX + NH2_ads",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.97e+22,'cm^2/(mol*s)'), n=0, Ea=(33771.5,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 1 HOX + H3NX <=> H2NX + H2OX in Surface_Abstraction_Single_vdW/training
    This reaction matched rate rule [NH3;*O-H]
    family: Surface_Abstraction_Single_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 1 HOX + H3NX <=> H2NX + H2OX in Surface_Abstraction_Single_vdW/training
This reaction matched rate rule [NH3;*O-H]
family: Surface_Abstraction_Single_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 6,
    label = "OX + NH2_ads <=> HOX + NH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.22e+21,'cm^2/(mol*s)'), n=0, Ea=(78156.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 6 H2NX + O* <=> OH* + HNX in Surface_Abstraction/training
    This reaction matched rate rule [O;*-N-H]
    family: Surface_Abstraction
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 6 H2NX + O* <=> OH* + HNX in Surface_Abstraction/training
This reaction matched rate rule [O;*-N-H]
family: Surface_Abstraction
metal: None
facet: None
site: None
""",
)

entry(
    index = 7,
    label = "NH2_ads + NH2_ads <=> NH_ads + NH3_ads",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.16e+20,'cm^2/(mol*s)'), n=0.667, Ea=(43420,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*=NH]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*=NH]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 8,
    label = "HOX + NH2_ads <=> NH_ads + H2OX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.04e+21,'cm^2/(mol*s)'), n=0, Ea=(964.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 9 H2NX-2 + OH_2* <=> H2O* + HNX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=NH]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 9 H2NX-2 + OH_2* <=> H2O* + HNX in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=NH]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 9,
    label = "NH2_ads + NH2_ads <=> NH_ads + NH3_ads",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.16e+20,'cm^2/(mol*s)'), n=0.667, Ea=(43420,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*=NH]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*=NH]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 10,
    label = "OX + NH_ads <=> X + HN-O_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.03e+21,'cm^2/(mol*s)'), n=0, Ea=(90815.7,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 6 HNX + O* <=> HNOX + X_4 in Surface_Dissociation_Double_vdW/training
    This reaction matched rate rule [ONR;VacantSite]
    family: Surface_Dissociation_Double_vdW
    metal: None
    facet: None
    site: None
    Ea raised from 73.0 to 90.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 6 HNX + O* <=> HNOX + X_4 in Surface_Dissociation_Double_vdW/training
This reaction matched rate rule [ONR;VacantSite]
family: Surface_Dissociation_Double_vdW
metal: None
facet: None
site: None
Ea raised from 73.0 to 90.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 11,
    label = "OX + NH_ads <=> X + HN-O_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.03e+21,'cm^2/(mol*s)'), n=0, Ea=(90815.7,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 6 HNX + O* <=> HNOX + X_4 in Surface_Dissociation_Double_vdW/training
    This reaction matched rate rule [ONR;VacantSite]
    family: Surface_Dissociation_Double_vdW
    metal: None
    facet: None
    site: None
    Ea raised from 73.0 to 90.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 6 HNX + O* <=> HNOX + X_4 in Surface_Dissociation_Double_vdW/training
This reaction matched rate rule [ONR;VacantSite]
family: Surface_Dissociation_Double_vdW
metal: None
facet: None
site: None
Ea raised from 73.0 to 90.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 12,
    label = "X + NO <=> NO_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1.4917e-06, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 3 X + NO <=> NO_X in Surface_Adsorption_Single/training
    This reaction matched rate rule [N=O;VacantSite]
    family: Surface_Adsorption_Single
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 3 X + NO <=> NO_X in Surface_Adsorption_Single/training
This reaction matched rate rule [N=O;VacantSite]
family: Surface_Adsorption_Single
metal: None
facet: None
site: None
""",
)

entry(
    index = 13,
    label = "OX + HN-O_ads <=> NO_ads + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.05e+23,'cm^2/(mol*s)'), n=0, Ea=(11800,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 31 O* + HNOX <=> NOX + OH_4* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 31 O* + HNOX <=> NOX + OH_4* in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*=O]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 14,
    label = "HN-O_ads + NH2_ads <=> NO_ads + NH3_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.45e+19,'cm^2/(mol*s)'), n=0.156, Ea=(40.526,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 8 used for N-H;*NH2
    Exact match found for rate rule [N-H;*NH2]
    Euclidian distance = 0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
From training reaction 8 used for N-H;*NH2
Exact match found for rate rule [N-H;*NH2]
Euclidian distance = 0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 15,
    label = "HOX + HN-O_ads <=> NO_ads + H2OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.56667e+21,'cm^2/(mol*s)'), n=0, Ea=(33.7715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [N-H;*O-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [N-H;*O-H]
Euclidian distance = 0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 16,
    label = "NH_ads + HN-O_ads <=> NO_ads + NH2_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.15895e+13,'m^2/(mol*s)'), n=0.820356, Ea=(91.6797,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 42 used for N-R;*=NH
    Exact match found for rate rule [N-R;*=NH]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 42 used for N-R;*=NH
Exact match found for rate rule [N-R;*=NH]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 17,
    label = "X + NO_ads <=> NO-h_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(20.6391,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 18,
    label = "OX + NH_ads <=> N_ads + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.14e+21,'cm^2/(mol*s)'), n=0, Ea=(154384,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 7 HNX-2 + O* <=> OH* + NX in Surface_Abstraction/training
    This reaction matched rate rule [O;*=N-H]
    family: Surface_Abstraction
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 7 HNX-2 + O* <=> OH* + NX in Surface_Abstraction/training
This reaction matched rate rule [O;*=N-H]
family: Surface_Abstraction
metal: None
facet: None
site: None
""",
)

entry(
    index = 19,
    label = "NH_ads + NH2_ads <=> N_ads + NH3_ads",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.87e+21,'cm^2/(mol*s)'), n=0, Ea=(94560.2,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*#N]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*#N]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 20,
    label = "HOX + NH_ads <=> N_ads + H2OX",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.38e+21,'cm^2/(mol*s)'), n=0, Ea=(39560.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 10 HNX-2 + OH_2* <=> H2O* + NX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*#N]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 10 HNX-2 + OH_2* <=> H2O* + NX in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*#N]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 21,
    label = "N_ads + NH2_ads <=> NH_ads + NH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.22e+21,'cm^2/(mol*s)'), n=0, Ea=(78.1569,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 22,
    label = "N_ads + HN-O_ads <=> NO_ads + NH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.17675e+14,'m^2/(mol*s)'), n=0.208794, Ea=(118.607,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 50 used for N-R;*#N
    Exact match found for rate rule [N-R;*#N]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 50 used for N-R;*#N
Exact match found for rate rule [N-R;*#N]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 23,
    label = "NO-h_ads <=> OX + N_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(76.227,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 24,
    label = "NH_ads + NH2_ads <=> N_ads + NH3_ads",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.87e+21,'cm^2/(mol*s)'), n=0, Ea=(94560.2,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*#N]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*#N]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 25,
    label = "HOX + NH_ads <=> N_ads + H2OX",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.38e+21,'cm^2/(mol*s)'), n=0, Ea=(39560.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 10 HNX-2 + OH_2* <=> H2O* + NX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*#N]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 10 HNX-2 + OH_2* <=> H2O* + NX in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*#N]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 26,
    label = "X + X + N2 <=> [Pt]N=N[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.146, n=0.201, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
    Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 27,
    label = "N_ads + NO-h_ads <=> OX + [Pt]N=N[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.53491e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
""",
)

entry(
    index = 28,
    label = "[Pt]N=N[Pt] <=> N_ads + N_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(182.529,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation
    Ea raised from 178.1 to 182.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
Ea raised from 178.1 to 182.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 29,
    label = "X + N2 <=> NN_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5.5e-05, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 22 X + N2 <=> N2X in Surface_Adsorption_vdW/training
    This reaction matched rate rule [N#N;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 22 X + N2 <=> N2X in Surface_Adsorption_vdW/training
This reaction matched rate rule [N#N;VacantSite]
family: Surface_Adsorption_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 30,
    label = "X + NN_ads <=> [Pt]N=N[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_vdW_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_vdW_to_Bidentate
""",
)

entry(
    index = 31,
    label = "OX + NO_ads <=> X + NO2JX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.776e+22,'cm^2/(mol*s)'), n=0, Ea=(135945,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 17 NOX + OX <=> NO2X + X_4 in Surface_Dissociation/training
    This reaction matched rate rule [O-N=O;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None
    Ea raised from 115.8 to 135.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 17 NOX + OX <=> NO2X + X_4 in Surface_Dissociation/training
This reaction matched rate rule [O-N=O;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
Ea raised from 115.8 to 135.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 32,
    label = "OX + HX <=> X + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.28e+21,'cm^2/(mol*s)'), n=0, Ea=(11200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 33,
    label = "HX + HOX <=> X + H2OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.04e+21,'cm^2/(mol*s)'), n=0, Ea=(66220,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 34,
    label = "X + X + H2O <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.0609262, n=0.077, Ea=(61.9349,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 35,
    label = "X + X + NH3 <=> HX + NH2_ads",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=0.0913893, n=0.077, Ea=(18.828,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 36,
    label = "X + NH3_ads <=> HX + NH2_ads",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(2.255e+20,'cm^2/(mol*s)'), n=0, Ea=(93000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 11 X_4 + NH3_X <=> NH2_X + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [N-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 11 X_4 + NH3_X <=> NH2_X + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [N-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 37,
    label = "X + NH2_ads <=> HX + NH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.014e+21,'cm^2/(mol*s)'), n=0, Ea=(110000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 18 X_4 + NH2_X <=> NHX_1 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [N-H2;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 18 X_4 + NH2_X <=> NHX_1 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [N-H2;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 38,
    label = "X + NH_ads <=> N_ads + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.08997e+21,'cm^2/(mol*s)'), n=0, Ea=(118000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 19 X_4 + NHX_2 <=> NX + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [N-H;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 19 X_4 + NHX_2 <=> NX + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [N-H;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 39,
    label = "X + HN-O_ads <=> NO_ads + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.51667e+19,'cm^2/(mol*s)'), n=0, Ea=(93,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 11 used for N-H;VacantSite
    Exact match found for rate rule [N-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 11 used for N-H;VacantSite
Exact match found for rate rule [N-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 40,
    label = "OX + HN-O_ads <=> NO2JX + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.57245e+14,'m^2/(mol*s)'), n=0.427897, Ea=(63.609,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

