#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + NH3 <=> NH3_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.79731, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 1,
    label = "X + X + O2 <=> O_X + O_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01094, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 2,
    label = "O_X + NH3_X <=> OH_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.85e+23,'cm^2/(mol*s)'), n=0, Ea=(157000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 3,
    label = "O_X + NH2_X <=> OH_X + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+21,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 4,
    label = "O_X + NH_X <=> N_X + OH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+21,'cm^2/(mol*s)'), n=0, Ea=(58500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 5,
    label = "O_X + N_X <=> X + NO_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+21,'cm^2/(mol*s)'), n=0, Ea=(121200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 6,
    label = "O_X + NH_X <=> X + NHO_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+21,'cm^2/(mol*s)'), n=0, Ea=(73000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 7,
    label = "O_X + NHO_X <=> NO_X + OH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.05e+23,'cm^2/(mol*s)'), n=0, Ea=(118000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 8,
    label = "N_X + N_X <=> X + X + N2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+19,'cm^2/(mol*s)'), n=0, Ea=(79100,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 9,
    label = "N_X + NO_X <=> X + X + N2O",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+19,'cm^2/(mol*s)'), n=0, Ea=(92900,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 10,
    label = "X + N2O_X <=> O_X + N2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.01e+17,'cm^2/(mol*s)'), n=0, Ea=(72200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 11,
    label = "NO_X <=> X + NO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+16,'1/s'), n=0, Ea=(140000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 12,
    label = "OH_X + NH_X <=> N_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+21,'cm^2/(mol*s)'), n=0, Ea=(46000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 13,
    label = "O_X + H2O_X <=> OH_X + OH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.03e+19,'cm^2/(mol*s)'), n=0, Ea=(52700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 14,
    label = "H2O_X <=> X + H2O",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'1/s'), n=0, Ea=(40300,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Rebrov_Pt111
""",
)

entry(
    index = 15,
    label = "OH_X + NH3_X <=> H2O_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.97e+22,'cm^2/(mol*s)'), n=0, Ea=(33771.5,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 16,
    label = "OH_X + NH2_X <=> NH_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.04e+21,'cm^2/(mol*s)'), n=0, Ea=(964.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 17,
    label = "N_X + NO_X <=> X + N2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.73e+21,'cm^2/(mol*s)'), n=0, Ea=(164998,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 18,
    label = "N2O_X <=> X + N2O",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.4e+16,'1/s'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 19,
    label = "NH2_X + NH2_X <=> NH_X + NH3_X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.16e+20,'cm^2/(mol*s)'), n=0.667, Ea=(43420,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*=NH]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*=NH]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 20,
    label = "NH_X + NH2_X <=> N_X + NH3_X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3.87e+21,'cm^2/(mol*s)'), n=0, Ea=(94560.2,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*#N]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*#N]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 21,
    label = "NHO_X + NH2_X <=> NO_X + NH3_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.45e+19,'cm^2/(mol*s)'), n=0.156, Ea=(40.526,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 8 used for N-H;*NH2
    Exact match found for rate rule [N-H;*NH2]
    Euclidian distance = 0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
From training reaction 8 used for N-H;*NH2
Exact match found for rate rule [N-H;*NH2]
Euclidian distance = 0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 22,
    label = "X + X + N2O <=> O_X + N2_X",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(295.29,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ON;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ON;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 23,
    label = "N_X + NH2_X <=> NH_X + NH_X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.22e+21,'cm^2/(mol*s)'), n=0, Ea=(78.1569,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 24,
    label = "NH_X + NHO_X <=> NO_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.15895e+13,'m^2/(mol*s)'), n=0.820356, Ea=(91.6797,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 42 used for N-R;*=NH
    Exact match found for rate rule [N-R;*=NH]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 42 used for N-R;*=NH
Exact match found for rate rule [N-R;*=NH]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 25,
    label = "OH_X + NHO_X <=> NO_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.56667e+21,'cm^2/(mol*s)'), n=0, Ea=(33.7715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [N-H;*O-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [N-H;*O-H]
Euclidian distance = 0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 26,
    label = "N_X + NHO_X <=> NO_X + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.17675e+14,'m^2/(mol*s)'), n=0.208794, Ea=(118.607,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 50 used for N-R;*#N
    Exact match found for rate rule [N-R;*#N]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 50 used for N-R;*#N
Exact match found for rate rule [N-R;*#N]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 27,
    label = "O_X + HX <=> X + OH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.28e+21,'cm^2/(mol*s)'), n=0, Ea=(11200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 28,
    label = "HX + OH_X <=> X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.04e+21,'cm^2/(mol*s)'), n=0, Ea=(66220,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 29,
    label = "X + NH3_X <=> HX + NH2_X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(2.255e+20,'cm^2/(mol*s)'), n=0, Ea=(93000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 11 X_4 + NH3_X <=> NH2_X + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [N-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 11 X_4 + NH3_X <=> NH2_X + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [N-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 30,
    label = "X + NH2_X <=> HX + NH_X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.014e+21,'cm^2/(mol*s)'), n=0, Ea=(110000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 18 X_4 + NH2_X <=> NHX_1 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [N-H2;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 18 X_4 + NH2_X <=> NHX_1 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [N-H2;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 31,
    label = "X + NH_X <=> N_X + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.08997e+21,'cm^2/(mol*s)'), n=0, Ea=(118000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 19 X_4 + NHX_2 <=> NX + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [N-H;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 19 X_4 + NHX_2 <=> NX + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [N-H;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 32,
    label = "X + NHO_X <=> NO_X + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.51667e+19,'cm^2/(mol*s)'), n=0, Ea=(93,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 11 used for N-H;VacantSite
    Exact match found for rate rule [N-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 11 used for N-H;VacantSite
Exact match found for rate rule [N-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 33,
    label = "X + X + H2O <=> HX + OH_X",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.0609262, n=0.077, Ea=(61.9349,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 34,
    label = "X + X + NH3 <=> HX + NH2_X",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=0.0913893, n=0.077, Ea=(18.828,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 35,
    label = "NO-h_ads <=> O_X + N_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(76.227,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 36,
    label = "X + NO_X <=> NO-h_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(20.6391,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 37,
    label = "NO-h_ads <=> O_X + N_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(76.227,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 38,
    label = "[Pt]=NN=[Pt] <=> N_X + N_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.77e+11,'1/s'), n=0.06, Ea=(452538,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 3 N2X2 <=> NX-2 + NX in Surface_Bidentate_Dissociation/training
    This reaction matched rate rule [Combined]
    family: Surface_Bidentate_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 3 N2X2 <=> NX-2 + NX in Surface_Bidentate_Dissociation/training
This reaction matched rate rule [Combined]
family: Surface_Bidentate_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 39,
    label = "X + N2_X <=> [Pt]=NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(4.184,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 40,
    label = "X + X + N2 <=> [Pt]=NN=[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.146, n=0.201, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
    Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 41,
    label = "N_X + NO-h_ads <=> O_X + [Pt]=NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.53491e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
""",
)

entry(
    index = 42,
    label = "O_X + NO_X <=> X + NO2JX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.776e+22,'cm^2/(mol*s)'), n=0, Ea=(135945,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 17 NOX + OX <=> NO2X + X_4 in Surface_Dissociation/training
    This reaction matched rate rule [O-N=O;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None
    Ea raised from 115.8 to 135.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 17 NOX + OX <=> NO2X + X_4 in Surface_Dissociation/training
This reaction matched rate rule [O-N=O;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
Ea raised from 115.8 to 135.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 43,
    label = "O_X + NHO_X <=> NO2JX + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.57245e+14,'m^2/(mol*s)'), n=0.427897, Ea=(63.609,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 44,
    label = "O_X + NO_X <=> X + NO2JX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.776e+22,'cm^2/(mol*s)'), n=0, Ea=(135945,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 17 NOX + OX <=> NO2X + X_4 in Surface_Dissociation/training
    This reaction matched rate rule [O-N=O;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None
    Ea raised from 115.8 to 135.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 17 NOX + OX <=> NO2X + X_4 in Surface_Dissociation/training
This reaction matched rate rule [O-N=O;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
Ea raised from 115.8 to 135.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 45,
    label = "X + X + ONNO_cis <=> NO_X + NO_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0304631, n=0.077, Ea=(18.828,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 46,
    label = "NO + NO <=> ONNO_cis",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(5.1562e+30,'m^3/(mol*s)'), n=-7.48856, Ea=(5.63876,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.354218852058, var=34.8187486739, Tref=1000.0, N=6, data_mean=0.0, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0',), comment="""Estimated from node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
""",
)

entry(
    index = 47,
    label = "O2_ads <=> O_X + O_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(76.227,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 48,
    label = "O2_ads + N_X <=> O_X + NO-h_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(7.06982e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*R-O]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*R-O]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 49,
    label = "O2_ads <=> O_X + O_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(76.227,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 50,
    label = "N_X + NO_X <=> X + NNOJJX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4e+19,'cm^2/(mol*s)'), n=0, Ea=(29.608,'kcal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 58 NOX + NX <=> N2OX + X_4 in Surface_Dissociation/training
    This reaction matched rate rule [N-N;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None
    Ea raised from 82.8 to 123.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 58 NOX + NX <=> N2OX + X_4 in Surface_Dissociation/training
This reaction matched rate rule [N-N;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
Ea raised from 82.8 to 123.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 51,
    label = "N_X + NHO_X <=> NNOJJX + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5.90531e+12,'m^2/(mol*s)'), n=0.618666, Ea=(106.039,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*#N]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*#N]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 52,
    label = "N_X + NO2JX <=> O_X + NNOJJX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.53491e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
""",
)

entry(
    index = 53,
    label = "X + X + ONNO_cis <=> O_X + NNOJJX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ONR;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ONR;VacantSite1;VacantSite2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 54,
    label = "N_X + NO_X <=> X + NNOJJX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4e+19,'cm^2/(mol*s)'), n=0, Ea=(29.608,'kcal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 58 NOX + NX <=> N2OX + X_4 in Surface_Dissociation/training
    This reaction matched rate rule [N-N;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None
    Ea raised from 82.8 to 123.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 58 NOX + NX <=> N2OX + X_4 in Surface_Dissociation/training
This reaction matched rate rule [N-N;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
Ea raised from 82.8 to 123.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 55,
    label = "X + N2O_X <=> N2OXX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_vdW_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_vdW_to_Bidentate
""",
)

entry(
    index = 56,
    label = "X + X + N2O <=> N2OXX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.073, n=0.201, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
    Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 57,
    label = "X + NNOJJX <=> N2OXX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(4.184,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 58,
    label = "N2OXX-2 <=> O_X + N2_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(440.977,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 59,
    label = "X + N2O_X <=> N2OXX-2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_vdW_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_vdW_to_Bidentate
""",
)

entry(
    index = 60,
    label = "X + X + N2O <=> N2OXX-2",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.073, n=0.201, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
    Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite1;VacantSite2
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 61,
    label = "NO-h_ads + N2_X <=> N_X + N2OXX-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.53491e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [N=*;*R-O]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [N=*;*R-O]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction
""",
)

entry(
    index = 62,
    label = "O2_ads + N2_X <=> O_X + N2OXX-2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(7.06982e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [N=*;*R-O]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [N=*;*R-O]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 63,
    label = "N2OXX-2 <=> O_X + N2_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.39e+11,'1/s'), n=0.299, Ea=(440.977,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Combined
    Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
From training reaction 1 used for Combined
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 64,
    label = "X + OH(D) <=> OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = StickingCoefficient(A=0.999, n=2, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 2 X + HO <=> HOX in Surface_Adsorption_Single/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Adsorption_Single
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 2 X + HO <=> HOX in Surface_Adsorption_Single/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Adsorption_Single
metal: None
facet: None
site: None
""",
)

entry(
    index = 65,
    label = "X + OH(D) <=> OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = StickingCoefficient(A=0.999, n=2, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 2 X + HO <=> HOX in Surface_Adsorption_Single/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Adsorption_Single
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 2 X + HO <=> HOX in Surface_Adsorption_Single/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Adsorption_Single
metal: None
facet: None
site: None
""",
)

entry(
    index = 66,
    label = "X + X + HONO <=> NO_X + OH_X",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.0152315, n=0.077, Ea=(18.828,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-N;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-N;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 67,
    label = "X + X + HONO <=> NO2JX + HX",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.0152315, n=0.077, Ea=(18.828,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 68,
    label = "NO + OH(D) <=> HONO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.74236e+06,'m^3/(mol*s)'), n=0.142499, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.0607054911525, var=1.94482475529, Tref=1000.0, N=4, data_mean=0.0, correlation='Root_N-1R->H_1CNOS->N_Ext-1N-R',), comment="""Estimated from node Root_N-1R->H_1CNOS->N_Ext-1N-R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_1CNOS->N_Ext-1N-R
""",
)

entry(
    index = 69,
    label = "X + HONO-2 <=> NO_X + OH_X",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(6.61e+17,'cm^2/(mol*s)'), n=1.589, Ea=(66.578,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 29 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 29 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 70,
    label = "HX + HONO-2 <=> OH_X + NHO_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(60.9818,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O-R;Abstracting] for rate rule [O-N=R;Abstracting]
    Euclidian distance = 2.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Abstracting] for rate rule [O-N=R;Abstracting]
Euclidian distance = 2.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 71,
    label = "HX + HONO-2 <=> NO_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(9.48698e+16,'m^2/(mol*s)'), n=0.0693333, Ea=(36.7735,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N-R;Abstracting] for rate rule [N-O;Abstracting]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;Abstracting] for rate rule [N-O;Abstracting]
Euclidian distance = 1.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 72,
    label = "HONO-2 + NH2_X <=> NO2JX + NH3_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.45e+19,'cm^2/(mol*s)'), n=0.156, Ea=(40.526,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;*NH2] for rate rule [O-H;*NH2]
    Euclidian distance = 2.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [Donating;*NH2] for rate rule [O-H;*NH2]
Euclidian distance = 2.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 73,
    label = "NH_X + HONO-2 <=> NO2JX + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.24812e+12,'m^2/(mol*s)'), n=0.968861, Ea=(79.0883,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 9 used for O-R;*=NH
    Exact match found for rate rule [O-R;*=NH]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 9 used for O-R;*=NH
Exact match found for rate rule [O-R;*=NH]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 74,
    label = "O_X + HONO-2 <=> NO2JX + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.015e+19,'cm^2/(mol*s)'), n=0, Ea=(52.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;*=O] for rate rule [O-N=R;*=O]
    Euclidian distance = 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=O] for rate rule [O-N=R;*=O]
Euclidian distance = 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 75,
    label = "O_X + HONO-2 <=> NO2JX + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.015e+19,'cm^2/(mol*s)'), n=0, Ea=(52.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 33 used for O-R;*=O
    Exact match found for rate rule [O-R;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 33 used for O-R;*=O
Exact match found for rate rule [O-R;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 76,
    label = "N_X + HONO-2 <=> NO2JX + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.09775e+11,'m^2/(mol*s)'), n=1.02854, Ea=(93.4698,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 10 used for O-R;*#N
    Exact match found for rate rule [O-R;*#N]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 10 used for O-R;*#N
Exact match found for rate rule [O-R;*#N]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 77,
    label = "NO2JX + NHO_X <=> NO_X + HONO-2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.56667e+17,'m^2/(mol*s)'), n=0, Ea=(33.7715,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N-H;*O] for rate rule [N-H;*O-N]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using template [N-H;*O] for rate rule [N-H;*O-N]
Euclidian distance = 1.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 78,
    label = "OH_X + HONO-2 <=> NO2JX + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.62399e+16,'m^2/(mol*s)'), n=0, Ea=(39.5839,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Donating;*O-H] + [O-H;Abstracting] for rate rule [O-H;*O-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction_Single_vdW"""),
    longDesc = 
"""
Estimated using average of templates [Donating;*O-H] + [O-H;Abstracting] for rate rule [O-H;*O-H]
Euclidian distance = 2.0
family: Surface_Abstraction_Single_vdW
""",
)

entry(
    index = 79,
    label = "X + HONO-2 <=> NO2JX + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.885e+21,'cm^2/(mol*s)'), n=-0.118, Ea=(74.4752,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 22 used for O-H;VacantSite
    Exact match found for rate rule [O-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 22 used for O-H;VacantSite
Exact match found for rate rule [O-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 80,
    label = "N_X + HONO-2 <=> NNOJJX + OH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.09775e+11,'m^2/(mol*s)'), n=1.02854, Ea=(93.4698,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*#N] for rate rule [O-N=R;*#N]
    Euclidian distance = 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*#N] for rate rule [O-N=R;*#N]
Euclidian distance = 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 81,
    label = "X + HONO <=> HONO-2",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.334, n=0.258, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 15 used for O-H;VacantSite
    Exact match found for rate rule [O-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 15 used for O-H;VacantSite
Exact match found for rate rule [O-H;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 82,
    label = "O_X + HONO-2 <=> NO2JX + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.015e+19,'cm^2/(mol*s)'), n=0, Ea=(52.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;*=O] for rate rule [O-N=R;*=O]
    Euclidian distance = 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=O] for rate rule [O-N=R;*=O]
Euclidian distance = 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 83,
    label = "O_X + HONO-2 <=> NO2JX + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.015e+19,'cm^2/(mol*s)'), n=0, Ea=(52.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 33 used for O-R;*=O
    Exact match found for rate rule [O-R;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 33 used for O-R;*=O
Exact match found for rate rule [O-R;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 84,
    label = "X + HONO-2 <=> NO_X + OH_X",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(6.61e+17,'cm^2/(mol*s)'), n=1.589, Ea=(66.578,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 29 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 29 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 85,
    label = "X + N2 <=> NN_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5.5e-05, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 22 X + N2 <=> N2X in Surface_Adsorption_vdW/training
    This reaction matched rate rule [N#N;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 22 X + N2 <=> N2X in Surface_Adsorption_vdW/training
This reaction matched rate rule [N#N;VacantSite]
family: Surface_Adsorption_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 86,
    label = "X + NN_ads <=> [Pt]=NN=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_vdW_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_vdW_to_Bidentate
""",
)

entry(
    index = 87,
    label = "X + OOH_ads <=> O_X + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.23586e+17,'m^2/(mol*s)'), n=0.624, Ea=(130.107,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 88,
    label = "O_X + H2O_X <=> HX + OOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(5.1449e+14,'m^2/(mol*s)'), n=0.427897, Ea=(252.034,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 89,
    label = "O_X + HONO-2 <=> NO_X + OOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.36667e+20,'cm^2/(mol*s)'), n=0, Ea=(67.543,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [N-R;*=O] for rate rule [N-O;*=O]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;*=O] for rate rule [N-O;*=O]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 90,
    label = "X + OOH_ads <=> O_X + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.23586e+17,'m^2/(mol*s)'), n=0.624, Ea=(130.107,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 91,
    label = "X + NOH_ads <=> N_X + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.34e+17,'cm^2/(mol*s)'), n=1.942, Ea=(121.577,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 49 used for N;VacantSite
    Exact match found for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 49 used for N;VacantSite
Exact match found for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 92,
    label = "N_X + H2O_X <=> HX + NOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.18106e+13,'m^2/(mol*s)'), n=0.618666, Ea=(115.198,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*#N]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 114.7 to 115.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*#N]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 114.7 to 115.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 93,
    label = "NO_X + HX <=> X + NOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.65488e+17,'m^2/(mol*s)'), n=0.195797, Ea=(114.453,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [*N;H-*]
    Euclidian distance = 0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using an average for rate rule [*N;H-*]
Euclidian distance = 0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 94,
    label = "X + X + HONO <=> O_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ONR;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [ONR;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 95,
    label = "N_X + HONO-2 <=> NO_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.17675e+14,'m^2/(mol*s)'), n=0.208794, Ea=(118.607,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [N-R;*#N] for rate rule [N-O;*#N]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;*#N] for rate rule [N-O;*#N]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 96,
    label = "X + HONO-2 <=> O_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.88316e+10,'m^2/(mol*s)'), n=1.39534, Ea=(-20.4157,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 6 used for ONR;VacantSite
    Exact match found for rate rule [ONR;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_Double_vdW"""),
    longDesc = 
"""
From training reaction 6 used for ONR;VacantSite
Exact match found for rate rule [ONR;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_Double_vdW
""",
)

entry(
    index = 97,
    label = "N_X + OOH_ads <=> O_X + NOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.53491e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(59.0521,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*O-OH]
    Euclidian distance = 4.242640687119285
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*O-OH]
Euclidian distance = 4.242640687119285
family: Surface_Abstraction
""",
)

entry(
    index = 98,
    label = "X + NOH_ads <=> N_X + OH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.34e+17,'cm^2/(mol*s)'), n=1.942, Ea=(121.577,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 49 used for N;VacantSite
    Exact match found for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 49 used for N;VacantSite
Exact match found for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

