#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + NH3 <=> NH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 1,
    label = "OX + NH3X <=> OHX + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.01e+21,'cm^2/(mol*s)'), n=0, Ea=(67543,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 2,
    label = "OX + NH2_X <=> OHX + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.22e+21,'cm^2/(mol*s)'), n=0, Ea=(78156.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 3,
    label = "OX + NH_X <=> NX + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.14e+21,'cm^2/(mol*s)'), n=0, Ea=(154384,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 4,
    label = "OHX + NH3X <=> H2O_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.97e+22,'cm^2/(mol*s)'), n=0, Ea=(33771.5,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 5,
    label = "OHX + NH2_X <=> NH_X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.04e+21,'cm^2/(mol*s)'), n=0, Ea=(964.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 6,
    label = "OHX + NH_X <=> NX + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.38e+21,'cm^2/(mol*s)'), n=0, Ea=(39560.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 7,
    label = "NX + NX <=> X + X + N2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.71e+21,'cm^2/(mol*s)'), n=0, Ea=(244120,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 8,
    label = "OX + NX <=> X + NOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.34e+21,'cm^2/(mol*s)'), n=0, Ea=(213243,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 9,
    label = "NOX <=> X + NO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.6e+17,'1/s'), n=0, Ea=(184296,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 10,
    label = "NX + NOX <=> X + N2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.73e+21,'cm^2/(mol*s)'), n=0, Ea=(164998,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 11,
    label = "N2O_X <=> X + N2O",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.4e+16,'1/s'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 12,
    label = "X + NH3X <=> H_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5.5e+20,'cm^2/(mol*s)'), n=0, Ea=(97454.9,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 13,
    label = "X + NH2_X <=> H_X + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.16e+21,'cm^2/(mol*s)'), n=0, Ea=(152454,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 14,
    label = "X + NH_X <=> NX + H_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.46e+21,'cm^2/(mol*s)'), n=0, Ea=(118683,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Schneider_Pt111
""",
)

entry(
    index = 15,
    label = "OX + H2O_X <=> OHX + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+20,'cm^2/(mol*s)'), n=0, Ea=(43100,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 16,
    label = "OX + H_X <=> X + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.28e+21,'cm^2/(mol*s)'), n=0, Ea=(11200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 17,
    label = "H_X + OHX <=> X + H2O_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.04e+21,'cm^2/(mol*s)'), n=0, Ea=(66220,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 18,
    label = "X + X + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.89e+21,'cm^5/(mol^2*s)'), n=-0.5, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 19,
    label = "X + H2O <=> H2O_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.75, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 20,
    label = "NH2_X + NH2_X <=> NH_X + NH3X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.16e+20,'cm^2/(mol*s)'), n=0.667, Ea=(43420,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*=NH]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 42 H2NX + H2NX-2 <=> H3NX + HNX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*=NH]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 21,
    label = "NH_X + NH2_X <=> NX + NH3X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3.87e+21,'cm^2/(mol*s)'), n=0, Ea=(94560.2,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*#N]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 50 HNX-2 + H2NX <=> H3NX + NX in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*#N]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 22,
    label = "X + X + NH3 <=> H_X + NH2_X",
    degeneracy = 1.5,
    kinetics = StickingCoefficient(A=0.0456946, n=0.077, Ea=(18.828,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 1.5
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 1.5
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 23,
    label = "NX + NH2_X <=> NH_X + NH_X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.22e+21,'cm^2/(mol*s)'), n=0, Ea=(78.1569,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 24,
    label = "X + X + H2O <=> H_X + OHX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.0609262, n=0.077, Ea=(61.9349,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction.
""",
)

